### ISSUE TITLE
Detecting Zerion doesn't work

### ISSUE THREAD

**Issue by thatdeji** [zeriontech/zerion-wallet-extension#480]
Zerion wallet extension is meant to inject an ethereum object to the window object in the browser when installed, which should expose an isZerion field as true [Reference](https://developers.zerion.io/reference/detecting-zerion). This is not the case, zerion wallet currently exposes isMetaMask field as true instead.

This makes it look like metamask was installed in the browser

![image](https://github.com/zeriontech/zerion-wallet-extension/assets/36773145/b9e52caf-0ba2-45a6-95aa-ce1e90a182a3)
Only Zerion wallet is installed on the browser and it still returns true for isMetaMask, and undefined for isZerion

@vyorkin @everdimension @zerts @abalyasnikov please can you look into this?

**Comment by zerts** [comment]
Hey @thatdeji !
Thank you for your question!

Right now this is a behaviour of extension if Metamask mode is enabled for this particular web site.

You can open extension and check the Metamask mode indicator if click on the button in the top left corner.

When Metamask mode turned off, all flags should appear in expected way.

Right now this disguise mode can be turned on automatically for the limited list of dapps that doesn't support injected wallet or Zerion wallet as an option.

**Comment by zerts** [comment]
You can check these flags in another dapps' dev tools. They should be correct by default for app.zerion.io (for example)

**Comment by thatdeji** [comment]
Hi @zerts , thanks!! This worked but instead of the ethereum.isZerion, it's exposing a zerionWallet object. Does that work?

Also, can this be included in the docs?

**Comment by zerts** [comment]
Hey @thatdeji !
`ethereum` object can be overwritten by other wallets.
We've added `zerionWallet` object for stable access to the provider, but this is not a standard way to use wallets. So we recommend checking `ethereum` wallet or using [eip6963](https://www.unblockcrypto.org) to access provider.

**Comment by thatdeji** [comment]
Hi @zerts, thanks again. I'm using this eip6963 approach, but it doesn't work for Zerion. You can use this eip6963 official [tutorial](https://main.eip-6963-tutorial.pages.dev/) to confirm too. Again, thanks, sorry if I'm disturbing.

**Comment by zerts** [comment]
May I ask what extension's version are you using?
eip6963 was supported by Zerion from the very beginning, so this is quite strange if it doesn't work well. I will check first thing tomorrow anyway.

**Comment by thatdeji** [comment]
I'm using version 1.4.0

**Comment by zerts** [comment]
What exact part of the tutorial doesn't work? 
<img width="646" alt="image" src="https://github.com/zeriontech/zerion-wallet-extension/assets/6473880/b8a5711d-6b02-463a-8bbd-3b0254b9351c">

**Comment by thatdeji** [comment]
Hi @zerts!, 
it works perfectly now. Thanks for your help!
